[package]
name = "lab8_ex3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md4 = "0.10.2"
rust-crypto = "0.2.36"
sha1 = "0.10.6"
sha2 = "0.10.8"
sha256 = "1.4.0"
